### ISSUE TITLE
Need guide.

### ISSUE THREAD

**Issue by Tamillogger** [iqrashjalil/MovieMingle-MERN_APP#1]
Bro add readme how to deploy this on vercel

**Comment by iqrashjalil** [comment]
### Deployment setup
const __filename = fileURLToPath(import.meta.url);
const __dirname1 = path.dirname(__filename);

### Reference the static files from the client build directory

app.use(express.static(path.join(__dirname1, "./frontend/dist")));

### Catch-all route to serve the index.html file
app.get("*", (req, res) => {
  res.sendFile(path.resolve(__dirname1, "./frontend/dist", "index.html"));
});
  
Add These Lines in your Index.js file in the backend and all good to go
